const test=require("node:test");
const assert=require("node:assert/strict");
const {createIsolatedDatabase}=require("./helpers/isolatedDatabase");
function reload(p){delete require.cache[require.resolve(p)];return require(p);}
function seed(db){
 db.prepare("INSERT INTO Guilds(id,name,created_at) VALUES('ga','A','now'),('gb','B','now')").run();
 db.prepare("INSERT INTO UsersV2(id,discord_user_id,created_at,updated_at) VALUES(101,'ua','now','now'),(102,'ub','now','now'),(103,'uc','now','now')").run();
 for(const [id,owner] of [['a',101],['b',102],['c',103]]){
  db.prepare("INSERT INTO CharactersV2(id,owner_user_id,proxy_name,character_type,created_at,updated_at) VALUES(?,?,?,'personnage_joue','now','now')").run(`ch-${id}`,owner,id.toUpperCase());
  db.prepare("INSERT INTO CharacterContinuitiesV2(id,character_id,name,created_at,updated_at) VALUES(?,?,?,'now','now')").run(`co-${id}`,`ch-${id}`,id);
 }
 db.prepare("INSERT INTO CharacterContinuitiesV2(id,character_id,name,created_at,updated_at) VALUES('co-a2','ch-a','a2','now','now'),('co-b2','ch-b','b2','now','now'),('co-c2','ch-c','c2','now','now')").run();
 db.prepare("INSERT INTO RelationshipTypes(id,guild_id,key,label_a_to_b,label_b_to_a,is_symmetric,created_at) VALUES(901,'ga','parent','Parent','Enfant',0,'now'),(902,'gb','parent','Parent','Enfant',0,'now')").run();
}
function context(db,guild,key,parent=null){const Repo=reload("../src/v2/repositories/ContextRepository"),Service=reload("../src/v2/services/contexts/ContextService");return new Service(new Repo(db)).create({guildId:guild,key,name:key,parentContextId:parent});}
function install(db,ch,co,guild,ctx){return Number(db.prepare(`INSERT INTO CharacterGuildInstallationsV2(character_id,continuity_id,guild_id,status,visibility,proxy_enabled,installed_at,updated_at,context_id) VALUES(?,?,?,'approved','public',1,'now','now',?)`).run(ch,co,guild,ctx).lastInsertRowid);}

test("3E isole création, demandes, mutations et arbre familial par Installation",()=>{const h=createIsolatedDatabase({initializeSchema:true});try{const db=h.database;seed(db);const a1=context(db,'ga','a1'),a2=context(db,'ga','a2'),child=context(db,'ga','child',a1.id),b1=context(db,'gb','b1');const ia=install(db,'ch-a','co-a','ga',a1.id),ib=install(db,'ch-b','co-b','ga',a1.id),ic=install(db,'ch-c','co-c','ga',a1.id),ia2=install(db,'ch-a','co-a2','ga',a2.id),ib2=install(db,'ch-b','co-b2','ga',a2.id),ichild=install(db,'ch-c','co-c2','ga',child.id),ibg=install(db,'ch-b','co-b','gb',b1.id);reload("../src/v2/repositories/InstallationRelationshipSchema")(db);const m=reload("../src/v2/managers/RelationshipV2Manager");
 const r=m.create({guildId:'ga',contextId:a1.id,installationAId:ia,installationBId:ib,relationshipTypeId:901,createdBy:'ua'});assert.equal(r.context_id,a1.id);assert.throws(()=>m.create({guildId:'ga',contextId:a1.id,installationAId:ia,installationBId:ib2,relationshipTypeId:901,createdBy:'ua'}),/même Guild|Context/);assert.throws(()=>m.create({guildId:'ga',installationAId:ia,installationBId:ibg,relationshipTypeId:901,createdBy:'ua'}),/même Guild|Context/);assert.throws(()=>m.create({guildId:'ga',installationAId:ib,installationBId:ia,relationshipTypeId:901,createdBy:'ub'}),/existe/);
 const r2=m.create({guildId:'ga',contextId:a2.id,installationAId:ia2,installationBId:ib2,relationshipTypeId:901,createdBy:'ua'});assert.equal(r2.context_id,a2.id);assert.equal(m.getForInstallationInContext(ia,'ga',a1.id).length,1);assert.equal(m.getForInstallationInContext(ia2,'ga',a2.id).length,1);
 const req=m.createRequest({guildId:'ga',contextId:a1.id,requesterInstallationId:ib,targetInstallationId:ic,relationshipTypeId:901,requestedBy:'ub',targetOwnerId:'uc'});assert.equal(req.context_id,a1.id);assert.throws(()=>m.acceptRequest(req.id,'uc',{guildId:'ga',contextId:a2.id}),/Context/);db.transaction(()=>{db.prepare("UPDATE Contexts SET is_default=0 WHERE guild_id='ga'").run();db.prepare("UPDATE Contexts SET is_default=1 WHERE id=?").run(a2.id);})();const accepted=m.acceptRequest(req.id,'uc');assert.equal(accepted.relationship.context_id,a1.id);
 assert.throws(()=>m.update(r2.id,{note:'forged'},{guildId:'ga',contextId:a1.id}),/Context/);m.update(r.id,{note:'ok'},{guildId:'ga',contextId:a1.id});assert.equal(m.getById(r.id).note,'ok');assert.throws(()=>db.prepare("UPDATE InstallationRelationshipsV2 SET context_id=? WHERE id=?").run(a2.id,r.id),/immutable/);
 const tree=m.getFamilyTree(ia,'ga',a1.id);assert.ok(tree.length);assert.equal(JSON.stringify(tree).includes(String(ia2)),false);assert.equal(m.getFamilyTree(ichild,'ga',child.id).length,0);db.prepare("UPDATE Contexts SET is_active=0,is_default=0 WHERE id=?").run(a1.id);assert.throws(()=>m.createRequest({guildId:'ga',contextId:a1.id,requesterInstallationId:ia,targetInstallationId:ic,relationshipTypeId:901,requestedBy:'ua',targetOwnerId:'uc'}),/inactif/);
 assert.equal(db.pragma('integrity_check',{simple:true}),'ok');}finally{h.cleanup();}});

test("3E migre seulement le legacy déterministe et reste idempotent",()=>{const h=createIsolatedDatabase({initializeSchema:true});try{const db=h.database;seed(db);const a1=context(db,'ga','a1'),a2=context(db,'ga','a2');install(db,'ch-a','co-a','ga',a1.id);install(db,'ch-b','co-b','ga',a1.id);install(db,'ch-c','co-c','ga',a2.id);db.prepare(`INSERT INTO ContinuityRelationshipsV2(id,guild_id,character_a_id,continuity_a_id,character_b_id,continuity_b_id,relationship_type_id,note,started_at,ended_at,created_by,created_at,updated_at) VALUES(701,'ga','ch-a','co-a','ch-b','co-b',901,'lore','2026-01-01','2026-02-01','ua','created','updated'),(702,'ga','ch-a','co-a','ch-c','co-c',901,'ambiguous',NULL,NULL,'ua','then','then')`).run();db.prepare(`INSERT INTO PendingContinuityRelationshipsV2(id,requester_continuity_id,target_continuity_id,relationship_type_id,requested_by,target_owner_id,note,started_at,status,created_at,responded_at,responded_by) VALUES(801,'co-a','co-b',901,'ua','ub','request lore','2026-03-01','rejected','requested','responded','uc'),(802,'co-a','co-c',901,'ua','uc',NULL,NULL,'pending','then',NULL,NULL)`).run();const init=reload("../src/v2/repositories/InstallationRelationshipSchema");init(db);const counts=[db.prepare("SELECT COUNT(*) n FROM InstallationRelationshipsV2").get().n,db.prepare("SELECT COUNT(*) n FROM PendingInstallationRelationshipsV2").get().n];const migratedRelation=db.prepare("SELECT * FROM InstallationRelationshipsV2 WHERE legacy_relationship_id=701").get(),migratedRequest=db.prepare("SELECT * FROM PendingInstallationRelationshipsV2 WHERE legacy_request_id=801").get();init(db);assert.deepEqual(counts,[1,1]);assert.equal(db.prepare("SELECT COUNT(*) n FROM ContinuityRelationshipsV2").get().n,2);assert.equal(db.prepare("SELECT COUNT(*) n FROM PendingContinuityRelationshipsV2").get().n,2);assert.deepEqual([migratedRelation.note,migratedRelation.started_at,migratedRelation.ended_at,migratedRelation.created_by,migratedRelation.created_at,migratedRelation.updated_at],['lore','2026-01-01','2026-02-01','ua','created','updated']);assert.deepEqual([migratedRequest.requested_by,migratedRequest.target_owner_id,migratedRequest.note,migratedRequest.started_at,migratedRequest.status,migratedRequest.created_at,migratedRequest.responded_at,migratedRequest.responded_by],['ua','ub','request lore','2026-03-01','rejected','requested','responded','uc']);assert.notEqual(migratedRelation.installation_a_id,migratedRelation.installation_b_id);assert.equal(migratedRelation.pair_low_installation_id,Math.min(migratedRelation.installation_a_id,migratedRelation.installation_b_id));assert.equal(db.pragma('integrity_check',{simple:true}),'ok');}finally{h.cleanup();}});

test("3E bootstrap réel x2 conserve legacy et mappings",()=>{const h=createIsolatedDatabase({copyExisting:true});try{const db=h.database;const beforeR=db.prepare("SELECT COUNT(*) n FROM ContinuityRelationshipsV2").get().n,beforeP=db.prepare("SELECT COUNT(*) n FROM PendingContinuityRelationshipsV2").get().n;const schema=reload("../src/database/schema"),log=console.log;console.log=()=>{};try{schema.initializeDatabase();const first=[db.prepare("SELECT COUNT(*) n FROM InstallationRelationshipsV2").get().n,db.prepare("SELECT COUNT(*) n FROM PendingInstallationRelationshipsV2").get().n];schema.initializeDatabase();assert.deepEqual([db.prepare("SELECT COUNT(*) n FROM InstallationRelationshipsV2").get().n,db.prepare("SELECT COUNT(*) n FROM PendingInstallationRelationshipsV2").get().n],first);}finally{console.log=log;}assert.equal(db.prepare("SELECT COUNT(*) n FROM ContinuityRelationshipsV2").get().n,beforeR);assert.equal(db.prepare("SELECT COUNT(*) n FROM PendingContinuityRelationshipsV2").get().n,beforeP);assert.equal(db.pragma('integrity_check',{simple:true}),'ok');}finally{h.cleanup();}});

test("3E préserve orientation, cycles actifs et atomicité des demandes",()=>{const h=createIsolatedDatabase({initializeSchema:true});try{const db=h.database;seed(db);const a1=context(db,'ga','a1'),a2=context(db,'ga','a2');const ia=install(db,'ch-a','co-a','ga',a1.id),ib=install(db,'ch-b','co-b','ga',a1.id),ic=install(db,'ch-c','co-c','ga',a1.id),ia2=install(db,'ch-a','co-a2','ga',a2.id),ib2=install(db,'ch-b','co-b2','ga',a2.id);reload("../src/v2/repositories/InstallationRelationshipSchema")(db);reload("../src/v2/repositories/InstallationRelationshipRepository");reload("../src/v2/repositories/RelationshipTypeRepository");reload("../src/v2/managers/InstallationRelationshipV2Manager");const m=reload("../src/v2/managers/RelationshipV2Manager");
 const oriented=m.create({guildId:'ga',contextId:a1.id,installationAId:ib,installationBId:ia,relationshipTypeId:901,createdBy:'ub'});assert.equal(oriented.installation_a_id,ib);assert.equal(oriented.installation_b_id,ia);assert.equal(m.toDisplayRelationship(oriented,'co-b').displayLabel,'Parent');assert.equal(m.toDisplayRelationship(oriented,'co-a').displayLabel,'Enfant');assert.throws(()=>m.create({guildId:'ga',contextId:a1.id,installationAId:ia,installationBId:ib,relationshipTypeId:901,createdBy:'ua'}),/existe/);m.end(oriented.id,{guildId:'ga',contextId:a1.id});const renewed=m.create({guildId:'ga',contextId:a1.id,installationAId:ia,installationBId:ib,relationshipTypeId:901,createdBy:'ua'});assert.equal(renewed.installation_a_id,ia);
 const pending=m.createRequest({guildId:'ga',contextId:a1.id,requesterInstallationId:ib,targetInstallationId:ic,relationshipTypeId:901,requestedBy:'ub',targetOwnerId:'uc'});assert.throws(()=>m.createRequest({guildId:'ga',contextId:a1.id,requesterInstallationId:ic,targetInstallationId:ib,relationshipTypeId:901,requestedBy:'uc',targetOwnerId:'ub'}),/attente/);m.rejectRequest(pending.id,'uc',{guildId:'ga',contextId:a1.id});const retry=m.createRequest({guildId:'ga',contextId:a1.id,requesterInstallationId:ib,targetInstallationId:ic,relationshipTypeId:901,requestedBy:'ub',targetOwnerId:'uc'});assert.equal(retry.status,'pending');
 const atomic=m.createRequest({guildId:'ga',contextId:a1.id,requesterInstallationId:ia,targetInstallationId:ic,relationshipTypeId:901,requestedBy:'ua',targetOwnerId:'uc'});db.exec(`CREATE TRIGGER fail_accept BEFORE UPDATE OF status ON PendingInstallationRelationshipsV2 WHEN NEW.id=${atomic.id} AND NEW.status='accepted' BEGIN SELECT RAISE(ABORT,'forced accept failure'); END;`);assert.throws(()=>m.acceptRequest(atomic.id,'uc',{guildId:'ga',contextId:a1.id}),/forced/);assert.equal(m.getRequestById(atomic.id).status,'pending');assert.equal(m.hasActiveRelationship({guildId:'ga',contextId:a1.id,installationAId:ia,installationBId:ic,relationshipTypeId:901}),undefined);db.exec("DROP TRIGGER fail_accept");
 m.create({guildId:'ga',contextId:a1.id,installationAId:ib,installationBId:ic,relationshipTypeId:901,createdBy:'ub'});const tree=JSON.stringify(m.getFamilyTree(ia,'ga',a1.id));assert.match(tree,/ch-c/);m.create({guildId:'ga',contextId:a2.id,installationAId:ia2,installationBId:ib2,relationshipTypeId:901,createdBy:'ua'});assert.equal(JSON.stringify(m.getFamilyTree(ia,'ga',a1.id)).includes('co-a2'),false);db.prepare(`INSERT INTO ContinuityRelationshipsV2(guild_id,character_a_id,continuity_a_id,character_b_id,continuity_b_id,relationship_type_id,created_by,created_at,updated_at) VALUES('ga','ch-a','co-a','ch-c','co-c',901,'ua','now','now')`).run();assert.equal(JSON.stringify(m.getFamilyTree(ia,'ga',a1.id)),tree);
 db.prepare("UPDATE Contexts SET is_active=0,is_default=0 WHERE id=?").run(a1.id);assert.throws(()=>m.acceptRequest(retry.id,'uc',{guildId:'ga',contextId:a1.id}),/inactif/);assert.equal(m.rejectRequest(retry.id,'uc',{guildId:'ga',contextId:a1.id}).status,'rejected');assert.equal(db.pragma('integrity_check',{simple:true}),'ok');}finally{h.cleanup();}});

test("3E indexe les lectures runtime critiques",()=>{const h=createIsolatedDatabase({initializeSchema:true});try{const db=h.database;reload("../src/v2/repositories/InstallationRelationshipSchema")(db);const plan=(sql,args)=>db.prepare(`EXPLAIN QUERY PLAN ${sql}`).all(...args).map(row=>row.detail).join(' ');assert.match(plan("SELECT * FROM InstallationRelationshipsV2 WHERE guild_id=? AND context_id=? AND ended_at IS NULL",['g','c']),/idx_installation_relationships_scope/);assert.match(plan("SELECT id FROM InstallationRelationshipsV2 WHERE context_id=? AND relationship_type_id=? AND pair_low_installation_id=? AND pair_high_installation_id=? AND ended_at IS NULL",['c',1,2,3]),/idx_installation_relationships_active_pair/);assert.match(plan("SELECT * FROM InstallationRelationshipsV2 WHERE installation_a_id=? AND context_id=?",[1,'c']),/idx_installation_relationships_a/);assert.match(plan("SELECT * FROM PendingInstallationRelationshipsV2 WHERE requester_installation_id=? AND status='pending' AND context_id=?",[1,'c']),/idx_pending_installation_relationships_requester/);assert.match(plan("SELECT * FROM PendingInstallationRelationshipsV2 WHERE target_installation_id=? AND status='pending' AND context_id=?",[1,'c']),/idx_pending_installation_relationships_target/);}finally{h.cleanup();}});

test("3E retire les droits de réponse à un ancien propriétaire",()=>{const h=createIsolatedDatabase({initializeSchema:true});try{const db=h.database;seed(db);const a1=context(db,'ga','a1'),ia=install(db,'ch-a','co-a','ga',a1.id),ic=install(db,'ch-c','co-c','ga',a1.id);reload("../src/v2/repositories/InstallationRelationshipSchema")(db);reload("../src/v2/repositories/InstallationRelationshipRepository");reload("../src/v2/repositories/RelationshipTypeRepository");reload("../src/v2/managers/InstallationRelationshipV2Manager");const m=reload("../src/v2/managers/RelationshipV2Manager");const request=m.createRequest({guildId:'ga',contextId:a1.id,requesterInstallationId:ia,targetInstallationId:ic,relationshipTypeId:901,requestedBy:'ua',targetOwnerId:'uc'});db.prepare("INSERT INTO UsersV2(id,discord_user_id,created_at,updated_at) VALUES(104,'ud','now','now')").run();db.prepare("UPDATE CharactersV2 SET owner_user_id=104 WHERE id='ch-c'").run();assert.throws(()=>m.acceptRequest(request.id,'uc',{guildId:'ga',contextId:a1.id}),/propriétaire/);assert.throws(()=>m.rejectRequest(request.id,'uc',{guildId:'ga',contextId:a1.id}),/propriétaire/);assert.throws(()=>m.acceptRequest(request.id,'ud',{guildId:'ga',contextId:a1.id}),/propriétaire/);assert.equal(m.cancelPendingRequest(request.id,'ua',{guildId:'ga',contextId:a1.id}).id,request.id);assert.equal(m.getRequestById(request.id),undefined);}finally{h.cleanup();}});
