const test=require("node:test");
const assert=require("node:assert/strict");
const {createIsolatedDatabase}=require("./helpers/isolatedDatabase");
function reload(p){delete require.cache[require.resolve(p)];return require(p);}
function context(db,g,key,parent=null){const R=reload("../src/v2/repositories/ContextRepository"),S=reload("../src/v2/services/contexts/ContextService");return new S(new R(db)).create({guildId:g,key,name:key,parentContextId:parent});}
function seedBase(db){db.prepare("INSERT INTO Guilds(id,name,created_at) VALUES('g1','G1','now'),('g2','G2','now')").run();db.prepare("INSERT INTO UsersV2(id,discord_user_id,created_at,updated_at) VALUES(1,'u1','now','now'),(2,'u2','now','now')").run();for(const n of [1,2]){db.prepare("INSERT INTO CharactersV2(id,owner_user_id,proxy_name,character_type,created_at,updated_at) VALUES(?,?,?,'personnage_joue','now','now')").run(`ch${n}`,n,`P${n}`);for(const s of ['a','b'])db.prepare("INSERT INTO CharacterContinuitiesV2(id,character_id,name,created_at,updated_at) VALUES(?,?,?,'now','now')").run(`co${n}${s}`,`ch${n}`,`C${n}${s}`);} }
function install(db,ch,co,g,c){return Number(db.prepare(`INSERT INTO CharacterGuildInstallationsV2(character_id,continuity_id,guild_id,status,visibility,proxy_enabled,installed_at,updated_at,context_id) VALUES(?,?,?,'approved','public',1,'now','now',?)`).run(ch,co,g,c).lastInsertRowid);}
function type(db,g,name){return Number(db.prepare("INSERT INTO StateTypes(guild_id,name,emoji,color,created_by,created_at) VALUES(?,?,NULL,NULL,'u1','now')").run(g,name).lastInsertRowid);}
function managers(){reload("../src/v2/repositories/InstallationStateRepository");reload("../src/v2/repositories/InstallationOutfitRepository");reload("../src/v2/managers/InstallationStateV2Manager");reload("../src/v2/managers/InstallationOutfitV2Manager");return {states:reload("../src/v2/managers/StateV2Manager"),outfits:reload("../src/v2/managers/OutfitV2Manager")};}

test("3H isole States et Outfits par Installation, Context et propriétaire",()=>{const h=createIsolatedDatabase({initializeSchema:true});try{const db=h.database;seedBase(db);const a=context(db,"g1","a"),b=context(db,"g1","b"),child=context(db,"g1","child",a.id),g2=context(db,"g2","a");const ia=install(db,"ch1","co1a","g1",a.id),ib=install(db,"ch1","co1b","g1",b.id),ic=install(db,"ch2","co2a","g1",child.id),ig=install(db,"ch2","co2b","g2",g2.id);const ta=type(db,"g1","Blessé"),tb=type(db,"g2","Wanted");const {states,outfits}=managers();
 const sa=states.create({installationId:ia,guildId:"g1",contextId:a.id,stateTypeId:ta,createdBy:"u1"});const sb=states.create({installationId:ib,guildId:"g1",contextId:b.id,stateTypeId:ta,createdBy:"u1"});assert.equal(states.getActiveStates(ia).length,1);assert.equal(states.getActiveStates(ib).length,1);assert.equal(states.getActiveStates(ic).length,0);assert.throws(()=>states.create({installationId:ia,guildId:"g1",contextId:a.id,stateTypeId:ta,createdBy:"u1"}),/déjà/);assert.throws(()=>states.create({installationId:ia,guildId:"g1",contextId:a.id,stateTypeId:tb,createdBy:"u1"}),/serveur/);assert.throws(()=>states.updateState(sa.id,{installationId:ib,guildId:"g1",contextId:b.id,actorId:"u1",note:"x"}),/introuvable/);assert.throws(()=>states.deleteState(sa.id,{installationId:ia,guildId:"g1",contextId:a.id,actorId:"u2"}),/gérer/);
 const oa=outfits.createCurrent({installationId:ia,guildId:"g1",contextId:a.id,createdBy:"u1",imageUrl:"https://a/1.png"});const ob=outfits.createCurrent({installationId:ib,guildId:"g1",contextId:b.id,createdBy:"u1",imageUrl:"https://b/1.png"});const oa2=outfits.createCurrent({installationId:ia,guildId:"g1",contextId:a.id,createdBy:"u1",imageUrl:"https://a/2.png"});assert.equal(outfits.getCurrent(ia).id,oa2.id);assert.equal(outfits.getCurrent(ib).id,ob.id);assert.equal(outfits.getForInstallation(ic).length,0);assert.throws(()=>outfits.setCurrent(ob.id,{installationId:ia,guildId:"g1",contextId:a.id,actorId:"u1"}),/introuvable/);assert.throws(()=>outfits.delete(oa.id,{installationId:ig,guildId:"g2",contextId:g2.id,actorId:"u2"}),/introuvable/);
 db.transaction(()=>{db.prepare("UPDATE Contexts SET is_default=0 WHERE guild_id='g1'").run();db.prepare("UPDATE Contexts SET is_default=1 WHERE id=?").run(b.id);})();assert.equal(states.getById(sa.id).context_id,a.id);assert.equal(outfits.getById(oa2.id).context_id,a.id);db.prepare("UPDATE Contexts SET is_active=0,is_default=0 WHERE id=?").run(a.id);assert.equal(states.getActiveStates(ia).length,1);assert.equal(outfits.getCurrent(ia).id,oa2.id);assert.throws(()=>states.updateState(sa.id,{installationId:ia,guildId:"g1",contextId:a.id,actorId:"u1",note:"x"}),/inactif/);assert.throws(()=>outfits.setCurrent(oa.id,{installationId:ia,guildId:"g1",contextId:a.id,actorId:"u1"}),/inactif/);assert.equal(states.end(sa.id,{installationId:ia,guildId:"g1",contextId:a.id,actorId:"u1"}).ended_at!==null,true);outfits.delete(oa.id,{installationId:ia,guildId:"g1",contextId:a.id,actorId:"u1"});assert.equal(db.prepare("SELECT COUNT(*) n FROM ContinuityStatesV2").get().n,0);assert.equal(db.prepare("SELECT COUNT(*) n FROM ContinuityOutfitsV2").get().n,0);assert.equal(sb.installation_id,ib);
 }finally{h.cleanup();}});

test("3H migre uniquement les historiques déterministes et reste idempotent",()=>{const h=createIsolatedDatabase({initializeSchema:true});try{const db=h.database;seedBase(db);const a=context(db,"g1","a"),g2=context(db,"g2","a");const one=install(db,"ch1","co1a","g1",a.id);install(db,"ch2","co2a","g1",a.id);install(db,"ch2","co2a","g2",g2.id);const t1=type(db,"g1","Malade"),t2=type(db,"g2","Wanted");const s1=Number(db.prepare(`INSERT INTO ContinuityStatesV2(continuity_id,state_type_id,note,started_at,created_by,created_at,updated_at) VALUES('co1a',?,'n','2026-01-01','u1','c','u')`).run(t1).lastInsertRowid);db.prepare(`INSERT INTO ContinuityStatesV2(continuity_id,state_type_id,note,started_at,created_by,created_at,updated_at) VALUES('co1a',?,'x','2026-01-02','u1','c','u')`).run(t2);const o1=Number(db.prepare(`INSERT INTO ContinuityOutfitsV2(continuity_id,image_url,title,is_current,created_at,updated_at) VALUES('co1a','https://one','one',1,'c','u')`).run().lastInsertRowid);db.prepare(`INSERT INTO ContinuityOutfitsV2(continuity_id,image_url,title,is_current,created_at,updated_at) VALUES('co2a','https://many','many',1,'c','u')`).run();const initS=reload("../src/v2/repositories/InstallationStateSchema"),initO=reload("../src/v2/repositories/InstallationOutfitSchema");initS(db);initO(db);initS(db);initO(db);const rs=db.prepare("SELECT * FROM InstallationStatesV2").all(),ro=db.prepare("SELECT * FROM InstallationOutfitsV2").all();assert.equal(rs.length,1);assert.equal(rs[0].legacy_state_id,s1);assert.equal(rs[0].installation_id,one);assert.equal(ro.length,1);assert.equal(ro[0].legacy_outfit_id,o1);assert.equal(ro[0].is_current,1);assert.equal(db.prepare("SELECT COUNT(*) n FROM ContinuityStatesV2").get().n,2);assert.equal(db.prepare("SELECT COUNT(*) n FROM ContinuityOutfitsV2").get().n,2);const {states,outfits}=managers();assert.equal(states.getLegacyUnmigrated().length,1);assert.equal(outfits.getLegacyUnmigrated().length,1);assert.equal(db.pragma("integrity_check",{simple:true}),"ok");}finally{h.cleanup();}});

test("3H protège en base unicité, scope immutable et concurrence logique",()=>{const h=createIsolatedDatabase({initializeSchema:true});try{const db=h.database;seedBase(db);const a=context(db,"g1","a"),b=context(db,"g1","b");const ia=install(db,"ch1","co1a","g1",a.id),ib=install(db,"ch1","co1b","g1",b.id),t=type(db,"g1","Inconscient");const {states,outfits}=managers();const s=states.create({installationId:ia,guildId:"g1",contextId:a.id,stateTypeId:t,createdBy:"u1"});assert.throws(()=>states.create({installationId:ia,guildId:"g1",contextId:a.id,stateTypeId:t,createdBy:"u1"}),/déjà/);assert.throws(()=>db.prepare("UPDATE InstallationStatesV2 SET context_id=? WHERE id=?").run(b.id,s.id),/immutable/);assert.throws(()=>db.prepare(`INSERT INTO InstallationStatesV2(guild_id,context_id,installation_id,state_type_id,started_at,created_by,created_at,updated_at) VALUES('g1',?,?,?,'x','u1','c','u')`).run(b.id,ia,t),/scope/);const o1=outfits.createCurrent({installationId:ia,guildId:"g1",contextId:a.id,createdBy:"u1",imageUrl:"https://1"}),o2=outfits.createCurrent({installationId:ia,guildId:"g1",contextId:a.id,createdBy:"u1",imageUrl:"https://2"});outfits.setCurrent(o1.id,{installationId:ia,guildId:"g1",contextId:a.id,actorId:"u1"});outfits.setCurrent(o2.id,{installationId:ia,guildId:"g1",contextId:a.id,actorId:"u1"});assert.equal(db.prepare("SELECT COUNT(*) n FROM InstallationOutfitsV2 WHERE installation_id=? AND is_current=1").get(ia).n,1);assert.throws(()=>db.prepare("UPDATE InstallationOutfitsV2 SET installation_id=? WHERE id=?").run(ib,o2.id),/immutable/);assert.match(db.prepare("EXPLAIN QUERY PLAN SELECT * FROM InstallationStatesV2 WHERE installation_id=? AND ended_at IS NULL").all(ia).map(x=>x.detail).join(" "),/idx_installation_states_history|uq_installation_states_active/);assert.match(db.prepare("EXPLAIN QUERY PLAN SELECT * FROM InstallationOutfitsV2 WHERE installation_id=? AND is_current=1").all(ia).map(x=>x.detail).join(" "),/uq_installation_outfits_current|idx_installation_outfits_current/);}finally{h.cleanup();}});
