const db=new Proxy({}, {get(_target,key){const current=require("../../database/database");const value=current[key];return typeof value==="function"?value.bind(current):value;}});
const {randomUUID}=require("node:crypto");
const SELECT=`SELECT e.*,i.entity_definition_id,d.name entity_name,d.avatar_url,d.embed_color,i.is_active entity_enabled FROM ContextNarrativeEntityEventsV2 e JOIN NarrativeEntityInstancesV2 i ON i.id=e.instance_id JOIN NarrativeEntitiesV2 d ON d.id=i.entity_definition_id`;
class Repo{
 hydrate(r){return {...r,is_enabled:Number(r.is_enabled)===1,entity_enabled:Number(r.entity_enabled)===1,scopes:db.prepare("SELECT channel_id FROM ContextNarrativeEntityEventScopesV2 WHERE event_id=? ORDER BY channel_id").all(r.id).map(x=>x.channel_id)};}
 getEnabled(){return db.prepare(`${SELECT} JOIN Contexts c ON c.guild_id=e.guild_id AND c.id=e.context_id WHERE e.is_enabled=1 AND i.is_active=1 AND c.is_active=1 ORDER BY e.guild_id,e.context_id,e.name`).all().map(r=>this.hydrate(r));}
 get(guildId,contextId,id){const r=db.prepare(`${SELECT} WHERE e.guild_id=? AND e.context_id=? AND e.id=?`).get(guildId,contextId,id);return r?this.hydrate(r):null;}
 byInstance(guildId,contextId,instanceId){return db.prepare(`${SELECT} WHERE e.guild_id=? AND e.context_id=? AND e.instance_id=? ORDER BY e.name`).all(guildId,contextId,instanceId).map(r=>this.hydrate(r));}
 create(x){db.transaction(()=>{db.prepare(`INSERT INTO ContextNarrativeEntityEventsV2(id,instance_id,guild_id,context_id,name,calendar_rule,weekday_rule,time_rule,timezone,message_content,action_key,action_payload,is_enabled,created_by,created_at,updated_at) VALUES(@id,@instanceId,@guildId,@contextId,@name,@calendarRule,@weekdayRule,@timeRule,@timezone,@messageContent,@actionKey,@actionPayload,1,@createdBy,@now,@now)`).run(x);this.replaceScopes(x.id,x.guildId,x.contextId,x.scopeIds,x.now);})();return this.get(x.guildId,x.contextId,x.id);}
 replaceScopes(id,guildId,contextId,ids,now){db.prepare("DELETE FROM ContextNarrativeEntityEventScopesV2 WHERE event_id=?").run(id);const q=db.prepare("INSERT INTO ContextNarrativeEntityEventScopesV2(event_id,guild_id,context_id,channel_id,created_at) VALUES(?,?,?,?,?)");for(const x of ids)q.run(id,guildId,contextId,x,now);}
 toggle(row,now){db.prepare("UPDATE ContextNarrativeEntityEventsV2 SET is_enabled=?,updated_at=? WHERE id=?").run(row.is_enabled?0:1,now,row.id);return this.get(row.guild_id,row.context_id,row.id);}
 delete(row){return db.prepare("DELETE FROM ContextNarrativeEntityEventsV2 WHERE id=?").run(row.id).changes>0;}
 claimRun(e,key,channel,now){const token=randomUUID();return db.prepare(`INSERT OR IGNORE INTO ContextNarrativeEntityEventRunsV2(event_id,guild_id,context_id,run_key,channel_id,status,attempt_token,external_effect_attempted,lease_at,created_at) VALUES(?,?,?,?,?,'running',?,0,?,?)`).run(e.id,e.guild_id,e.context_id,key,channel,token,now,now).changes?token:null;}
 markExternalEffectAttempted(e,key,channel,token,now){return db.prepare(`UPDATE ContextNarrativeEntityEventRunsV2 SET external_effect_attempted=1,lease_at=? WHERE event_id=? AND guild_id=? AND context_id=? AND run_key=? AND channel_id=? AND status='running' AND attempt_token=?`).run(now,e.id,e.guild_id,e.context_id,key,channel,token).changes===1;}
 completeRun(e,key,channel,token,messageId,now){const ok=db.prepare(`UPDATE ContextNarrativeEntityEventRunsV2 SET status='sent',message_id=?,error_message=NULL WHERE event_id=? AND guild_id=? AND context_id=? AND run_key=? AND channel_id=? AND status='running' AND attempt_token=?`).run(messageId||null,e.id,e.guild_id,e.context_id,key,channel,token).changes===1;if(ok)db.prepare("UPDATE ContextNarrativeEntityEventsV2 SET last_run_key=?,updated_at=? WHERE id=?").run(key,now,e.id);return ok;}
 failRun(e,key,channel,token,error,now,uncertain=false){return db.prepare(`UPDATE ContextNarrativeEntityEventRunsV2 SET status=?,error_message=?,lease_at=? WHERE event_id=? AND guild_id=? AND context_id=? AND run_key=? AND channel_id=? AND status='running' AND attempt_token=?`).run(uncertain?'failed_uncertain':'failed',String(error).slice(0,1000),now,e.id,e.guild_id,e.context_id,key,channel,token).changes===1;}
 getStaleRunningRuns(before){return db.prepare(`SELECT * FROM ContextNarrativeEntityEventRunsV2 WHERE status='running' AND (lease_at IS NULL OR lease_at<=?) ORDER BY id`).all(before);}
 recoverRun(id,token,before,now){const next=randomUUID();return db.prepare(`UPDATE ContextNarrativeEntityEventRunsV2 SET attempt_token=?,lease_at=? WHERE id=? AND status='running' AND attempt_token=? AND external_effect_attempted=0 AND lease_at<=?`).run(next,now,id,token,before).changes?next:null;}
 markStaleRunUncertain(id,before,now){return db.prepare(`UPDATE ContextNarrativeEntityEventRunsV2 SET status='failed_uncertain',error_message=?,lease_at=? WHERE id=? AND status='running' AND (lease_at IS NULL OR lease_at<=?) AND (external_effect_attempted IS NULL OR external_effect_attempted=1)`).run("Exécution interrompue avec effet externe inconnu.",now,id,before).changes===1;}
}
module.exports=new Repo();
