const db=require('../../database/database');
const SELECT=`SELECT a.*,i.character_id,i.continuity_id,t.label type_label,t.emoji type_emoji,t.type_key,c.proxy_name owner_name,u.discord_user_id owner_discord_user_id,x.is_active context_is_active FROM InstallationAssetsV2 a JOIN CharacterGuildInstallationsV2 i ON i.id=a.installation_id JOIN Contexts x ON x.id=a.context_id JOIN AssetTypesV2 t ON t.id=a.asset_type_id JOIN CharactersV2 c ON c.id=i.character_id JOIN UsersV2 u ON u.id=c.owner_user_id`;
function getById(id){return db.prepare(`${SELECT} WHERE a.id=?`).get(id);}
function getInstallation(id){return db.prepare(`SELECT i.*,x.is_active context_is_active,c.is_archived,u.discord_user_id owner_discord_user_id FROM CharacterGuildInstallationsV2 i JOIN Contexts x ON x.id=i.context_id AND x.guild_id=i.guild_id JOIN CharactersV2 c ON c.id=i.character_id JOIN CharacterContinuitiesV2 co ON co.id=i.continuity_id AND co.character_id=i.character_id JOIN UsersV2 u ON u.id=c.owner_user_id WHERE i.id=?`).get(id);}
function candidates(guild,continuity,context=null){return db.prepare(`SELECT i.*,x.is_active context_is_active,c.is_archived,u.discord_user_id owner_discord_user_id FROM CharacterGuildInstallationsV2 i JOIN Contexts x ON x.id=i.context_id AND x.guild_id=i.guild_id JOIN CharactersV2 c ON c.id=i.character_id JOIN UsersV2 u ON u.id=c.owner_user_id WHERE i.guild_id=? AND i.continuity_id=? AND (? IS NULL OR i.context_id=?) ORDER BY i.id`).all(String(guild),continuity,context,context);}
function list(installation,context){return db.prepare(`${SELECT} WHERE a.installation_id=? AND a.context_id=? ORDER BY t.sort_order,t.label COLLATE NOCASE,a.name COLLATE NOCASE,a.id`).all(installation,context);}
function count(installation,context){return db.prepare("SELECT COUNT(*) n FROM InstallationAssetsV2 WHERE installation_id=? AND context_id=?").get(installation,context).n;}
function create(d){const r=db.prepare(`INSERT INTO InstallationAssetsV2(guild_id,context_id,installation_id,asset_type_id,name,description,details,image_url,created_by,created_at,updated_at)VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(String(d.guildId),d.contextId,d.installationId,d.assetTypeId,d.name,d.description,d.details,d.imageUrl,d.createdBy,d.createdAt,d.updatedAt);return getById(r.lastInsertRowid);}
function update(id,d){db.prepare("UPDATE InstallationAssetsV2 SET name=?,description=?,details=?,image_url=?,updated_at=? WHERE id=?").run(d.name,d.description,d.details,d.imageUrl,d.updatedAt,id);return getById(id);}
function transfer(asset,d){return db.transaction(()=>{const changed=db.prepare("UPDATE InstallationAssetsV2 SET installation_id=?,updated_at=? WHERE id=? AND installation_id=? AND context_id=?").run(d.toInstallationId,d.createdAt,asset.id,d.expectedInstallationId,asset.context_id);if(changed.changes!==1)throw new Error("Ce bien a été modifié ou transféré entre-temps. Actualisez la fiche avant de réessayer.");db.prepare(`INSERT INTO InstallationAssetTransfersV2(asset_id,guild_id,context_id,from_installation_id,to_installation_id,transferred_by,note,created_at)VALUES(?,?,?,?,?,?,?,?)`).run(asset.id,asset.guild_id,asset.context_id,d.expectedInstallationId,d.toInstallationId,d.transferredBy,d.note,d.createdAt);return getById(asset.id);})();}
function transfers(id,limit=20){return db.prepare(`SELECT h.*,fi.continuity_id from_continuity_id,ti.continuity_id to_continuity_id,fc.proxy_name from_character_name,tc.proxy_name to_character_name FROM InstallationAssetTransfersV2 h JOIN CharacterGuildInstallationsV2 fi ON fi.id=h.from_installation_id JOIN CharacterGuildInstallationsV2 ti ON ti.id=h.to_installation_id JOIN CharactersV2 fc ON fc.id=fi.character_id JOIN CharactersV2 tc ON tc.id=ti.character_id WHERE h.asset_id=? ORDER BY h.created_at DESC,h.id DESC LIMIT ?`).all(id,limit);}
function remove(id){return db.prepare("DELETE FROM InstallationAssetsV2 WHERE id=?").run(id);}
function legacyAssets(guild){return db.prepare("SELECT * FROM ContinuityAssetsV2 WHERE guild_id=? ORDER BY id").all(String(guild));}
function legacyTransfers(guild){return db.prepare("SELECT * FROM ContinuityAssetTransfersV2 WHERE guild_id=? ORDER BY id").all(String(guild));}
module.exports={getById,getInstallation,getCandidates:candidates,getForInstallation:list,countForInstallation:count,create,update,transfer,getTransfers:transfers,delete:remove,getLegacyAssets:legacyAssets,getLegacyTransfers:legacyTransfers};
