module.exports = Object.freeze([
    { key: "friend", labelAToB: "Ami·e de", labelBToA: "Ami·e de", isSymmetric: true },
    { key: "best_friend", labelAToB: "Meilleur·e ami·e de", labelBToA: "Meilleur·e ami·e de", isSymmetric: true },
    { key: "acquaintance", labelAToB: "Connaissance de", labelBToA: "Connaissance de", isSymmetric: true },
    { key: "ally", labelAToB: "Allié·e de", labelBToA: "Allié·e de", isSymmetric: true },
    { key: "rival", labelAToB: "Rival·e de", labelBToA: "Rival·e de", isSymmetric: true },
    { key: "enemy", labelAToB: "Ennemi·e de", labelBToA: "Ennemi·e de", isSymmetric: true },
    { key: "partner", labelAToB: "En couple avec", labelBToA: "En couple avec", isSymmetric: true },
    { key: "unacknowledged_couple", labelAToB: "En couple sans l'assumer avec", labelBToA: "En couple sans l'assumer avec", isSymmetric: true },
    { key: "sexfriend", labelAToB: "Friends with benefits de", labelBToA: "Friends with benefits de", isSymmetric: true },
    { key: "polyamorous_relationship", labelAToB: "En relation polyamoureuse avec", labelBToA: "En relation polyamoureuse avec", isSymmetric: true },
    { key: "spouse", labelAToB: "Marié·e à", labelBToA: "Marié·e à", isSymmetric: true },
    { key: "fiance", labelAToB: "Fiancé·e à", labelBToA: "Fiancé·e à", isSymmetric: true },
    { key: "ex", labelAToB: "Ex de", labelBToA: "Ex de", isSymmetric: true },
    { key: "flirt", labelAToB: "Flirte avec", labelBToA: "Flirte avec", isSymmetric: true },
    { key: "crush", labelAToB: "Attiré·e par", labelBToA: "Objet de l’attirance de", isSymmetric: false },
    { key: "secret_love", labelAToB: "Amoureux·se en secret de", labelBToA: "Aimé·e en secret par", isSymmetric: false },
    { key: "parent", labelAToB: "Parent de", labelBToA: "Enfant de", isSymmetric: false },
    { key: "sibling", labelAToB: "Frère/Sœur de", labelBToA: "Frère/Sœur de", isSymmetric: true },
    { key: "half_sibling", labelAToB: "Demi-frère/Demi-sœur de", labelBToA: "Demi-frère/Demi-sœur de", isSymmetric: true },
    { key: "sibling_in_law", labelAToB: "Beau-frère/Belle-sœur de", labelBToA: "Beau-frère/Belle-sœur de", isSymmetric: true },
    { key: "stepparent", labelAToB: "Beau-père/Belle-mère de", labelBToA: "Beau-fils/Belle-fille de", isSymmetric: false },
    { key: "cousin", labelAToB: "Cousin·e de", labelBToA: "Cousin·e de", isSymmetric: true },
    { key: "uncle_aunt", labelAToB: "Oncle/Tante de", labelBToA: "Neveu/Nièce de", isSymmetric: false },
    { key: "nephew_niece", labelAToB: "Neveu/Nièce de", labelBToA: "Oncle/Tante de", isSymmetric: false },
    { key: "godparent", labelAToB: "Parrain/Marraine de", labelBToA: "Filleul/Filleule de", isSymmetric: false },
    { key: "godchild", labelAToB: "Filleul/Filleule de", labelBToA: "Parrain/Marraine de", isSymmetric: false },
    { key: "grandparent", labelAToB: "Grand-parent de", labelBToA: "Petit-enfant de", isSymmetric: false },
    { key: "mentor", labelAToB: "Mentor de", labelBToA: "Protégé·e de", isSymmetric: false },
    { key: "boss", labelAToB: "Supérieur·e de", labelBToA: "Subordonné·e de", isSymmetric: false },
    { key: "colleague", labelAToB: "Collègue de", labelBToA: "Collègue de", isSymmetric: true },
    { key: "roommate", labelAToB: "Colocataire de", labelBToA: "Colocataire de", isSymmetric: true },
    { key: "associate", labelAToB: "Associé·e de", labelBToA: "Associé·e de", isSymmetric: true },
    { key: "protector", labelAToB: "Protecteur·rice de", labelBToA: "Protégé·e par", isSymmetric: false },
    { key: "bodyguard", labelAToB: "Garde du corps de", labelBToA: "Protégé·e de", isSymmetric: false },
    { key: "debtor", labelAToB: "Doit de l’argent à", labelBToA: "Créancier·ère de", isSymmetric: false },
    { key: "informant", labelAToB: "Informateur·rice de", labelBToA: "Contact de", isSymmetric: false },
    { key: "leader", labelAToB: "Dirige", labelBToA: "Sous les ordres de", isSymmetric: false },
    { key: "kidnapper", labelAToB: "Ravisseur·se de", labelBToA: "Captif·ve de", isSymmetric: false }
]);
